config/routes.rb
Rails.application.routes.draw do

  root 'sessions#new'

  resources :users do
    resources :tasks do
      member do
        get :complete
        get :like
      end
    end
  end

  get '/tags'     => 'tags#index'
  get '/tags/:id' => 'tags#show', as: "tag"
  get '/user/:id/tags' => 'tags#user_index', as: "user_tags"

  get '/tasks'   => 'tasks#index', as: "all_tasks"
  get '/welcome' => 'sessions#new'
  get '/home'    => 'users#home'
  post '/login'   => 'sessions#create'
  get '/logout'   => 'sessions#destroy'

end

app/models/like.rb
class Like < ActiveRecord::Base
  belongs_to :task
end

app/models/tag.rb
class Tag < ActiveRecord::Base
  has_many :taggings
  has_many :tasks, through: :taggings
end

app/models/tagging.rb
class Tagging < ActiveRecord::Base
  belongs_to :task
  belongs_to :tag
end

app/models/task.rb
class Task < ActiveRecord::Base
  belongs_to :user

  has_many :likes

  has_many :taggings
  has_many :tags, through: :taggings

  acts_as_votable

  def tag_list
    self.tags.collect do |tag|
      tag.content
    end.join(", ")
  end

  def tag_list=(tags_string)
    tag_names = tags_string.split(",").collect{ |s| s.strip.downcase }.uniq
    new_or_found_tags = tag_names.collect { |content| Tag.find_or_create_by(content: content) }
    self.tags = new_or_found_tags
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password

  validates :fname, :presence => { message: "first name is missing" }
  validates :lname, :presence => { message: "last name is missing" }
  validates :email, :presence => { message: "email is missing" },
                    :uniqueness => { message: "email is already used" }
  validates :password, :length => { in: 6..20, message: "password has to be between 6 and 20 characters" },
                       :presence => { message: "password can't be blank" }

  has_many :tasks
  has_many :likes, through: :tasks
  def score
    score = 0
    if tasks.size > 0
      tasks.each do |task|
        score += task.points.to_i
      end
    end
    return score
  end

  def likes
    total_likes = 0

    tasks.each do |task|
      total_likes += task.votes_for.size
    end

    return total_likes
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  helper_method :current_user

  def authorize
    if !current_user
      flash.notice = "Please log in first."
      redirect_to welcome_path
    end
  end
  helper_method :authorize

  def is_current_user?(user)
    current_user.id == user.id
  end
  helper_method :is_current_user?

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
    if current_user
      # redirect to homepage if user is logged in
      redirect_to user_path(current_user)
    else
      @user = User.new
    end
  end

  def create
    user = User.find_by email: params[:email]

    if user && user.authenticate(params[:password])
      # successful login
      session[:user_id] = user.id
      redirect_to user_path(user)
    else
      flash.notice = 'The email/password you\'ve entered is incorrect'
      redirect_to welcome_path
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to welcome_path
  end

end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  before_action :authorize

  def index
    clear_empty_tags
    @tags = Tag.all
  end

  def show
    @tag = Tag.find(params[:id])
  end

  def user_index
    @user = User.find(params[:id])
    @user_tags = @user.tasks.collect do |task|
      task.tags
    end.flatten
  end

  private
    def clear_empty_tags
      @tags = Tag.all

      @tags.each do |tag|
        tag.delete if tag.tasks.empty?
      end
    end

end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :authorize

  def index
    @play_tasks = Task.all.where(category: "play")
    @work_tasks = Task.all.where(category: "work")
  end

  def create
    @user = User.find(params[:user_id])
    @task = @user.tasks.create(task_params)

    # "play" = +1, "work" = -1
    @task.points = @task.category == "play" ? 1 : -1
    @task.save

    redirect_to user_path(@user)
  end

  def edit
    @task = Task.find(params[:id])
  end

  def update
    @task = Task.find(params[:id])

    if @task.update(task_params)
      @task.points = @task.category == "play" ? 1 : -1
      @task.save
      flash.notice = "task updated"
      redirect_to user_path(@task.user)
    end
  end

  def complete
    @task = Task.find(params[:id])

    @task.completed = true
    @task.save

    flash.notice = "Task marked as completed"
    redirect_to user_path(@task.user)
  end

  def destroy
    @task = Task.find(params[:id])
    @user = User.find(params[:user_id])

    @task.destroy
    flash.notice = "\'#{@task.description} \' deleted."
    redirect_to user_path(@user)
  end

  def like
    @task = Task.find(params[:id])
    @task.liked_by current_user

    redirect_to :back
  end

  private
    def task_params
      params.require(:task).permit(
        :description,
        :category,
        :points,
        :completed,
        :tag_list
      )
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authorize, except: :create

  def index
    @users = User.all.order(:fname)
    @users_score = @users.map do |user|
      user.score
    end.reduce(:+)

    @users_likes = @users.map do |user|
      user.likes
    end.reduce(:+)
  end

  def create
    @user = User.new(user_params)

    if @user.save
      session[:user_id] = @user.id
      redirect_to user_path(@user)
    else
      render "sessions/new"
    end
  end

  def show
    @user = User.find(params[:id])
    if is_current_user?(@user)
      redirect_to home_path
    else
      set_play_and_work_tasks
    end
  end

  def home
    @user = current_user
    set_play_and_work_tasks
  end

  private
    def user_params
      params.require(:user).permit(
        :fname,
        :lname,
        :email,
        :password,
        :password_confirmation
      )
    end

    def set_play_and_work_tasks
      @play_tasks = @user.tasks.where(category: "play").order(:completed, :description)
      @work_tasks = @user.tasks.where(category: "work").order(:completed, :description)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>WorkAndPlay</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css" type="text/css" rel="stylesheet">
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<% if current_user %>
  <nav class="navbar navbar-default">
    <ul class="nav navbar-nav">
      <li>
        <%= link_to home_path, class: "navbar-brand" do %>
          <span class="glyphicon glyphicon-home"></span>
        <% end %>
      </li>
      <li><%= link_to "All Users", users_path %></li>
      <li><%= link_to "All Tags", tags_path %></li>
      <li><%= link_to "Your Tags", user_tags_path(current_user) %></li>
      <li><%= link_to "All Tasks", all_tasks_path %></li>
    </ul>

    <ul class="nav navbar-nav pull-right">
        <li><%= link_to "Logout", logout_path %></li>
    </ul>
  </nav>
<% end %>

<p><%= flash.notice %></p>
<%= yield %>

</body>
</html>

app/views/tags/index.html.erb
<h1>All Tags (<%= @tags.size %>)</h1>
<ul>
  <% @tags.each do |tag| %>
    <li>
      <%= link_to tag.content, tag_path(tag) %> (<%= tag.tasks.size %>)
    </li>
  <% end %>
</ul>

app/views/tags/show.html.erb
<h1><%= @tag.content %> (<%= @tag.tasks.size %>)</h1>

<ul>
  <% @tag.tasks.each do |task| %>
    <li>
      <% if is_current_user?(task.user) %>
        <%= link_to "#{task.description} | YOU!", home_path %>
      <% else %>
        <%= link_to "#{task.description} |
          #{task.user.fname} #{task.user.lname}", user_path(task.user) %>
      <% end %>
    </li>
  <% end %>
</ul>

app/views/tags/user_index.html.erb
<h1><%= @user.fname %>'s Tags</h1>

<ul>
  <% @user_tags.each do |tag| %>
    <li>
      <%= link_to tag.content, tag_path(tag) %> (<%= tag.tasks.size %>)
    </li>
  <% end %>
</ul>

app/views/tasks/_form.html.erb
<div class="container">
  <div class="task_form">
    <%= form_for([@user, @user.tasks.build]) do |f| %>
      <div class="row", id="task-information-form">
        <p>
          <%= f.text_field :description, placeholder: "task description" %>
        </p>

        <p>
          <%= f.text_field :tag_list, placeholder: "enter list of tags" %>
        </p>

        <%= hidden_field_tag "task[category]", "#{category}" %>

        <p>
          <%= button_tag(type: 'submit', class: 'btn btn-default', id: 'add-button') do %>
            <span class="glyphicon glyphicon-plus"></span>
          <% end %>
        </p>
      </div>
    <% end %>

  </div>
</div>

app/views/tasks/_show.html.erb
<div class="container">
  <% object.each do |task| %>
    <% if task.completed %>
      <div class="task_show completed">
    <% else %>
      <div class="task_show outstanding">
    <% end %>

      <div class="row", id="upper-right-button">
        <% if is_current_user?(task.user) %>
          <%= link_to user_task_path(task.user, task), class: "btn btn-default pull-right", id: "delete-button", method: :delete do %>
            <span class="glyphicon glyphicon-remove"></span>
          <% end %>
        <% else %>
          <%= link_to like_user_task_path(task.user, task), class: "btn btn-default pull-right", id: "like-button" do %>
            <span class="glyphicon glyphicon-thumbs-up"></span>
          <% end %>
        <% end %>
      </div>

      <div class="row", id="task-information">
        <%= task.description %><br>
        <%= render partial: "tasks/tags", locals: { :task => task } %><br>

        <% if is_current_user?(task.user) %>
          <%= link_to edit_user_task_path(task.user, task), class: "btn btn-default" do %>
            <span class="glyphicon glyphicon-pencil"></span>
          <% end %>

          <% if !task.completed %>
            <%= link_to complete_user_task_path(task.user, task), class: "btn btn-default", id: "complete-button" do %>
              <span class="glyphicon glyphicon-ok"></span>
            <% end %>
          <% end %>
        <% end %>
        <br>
        <span class="glyphicon glyphicon-heart"></span>
        <%= "#{task.votes_for.size}" %>
      </div>

      <br>
    </div>
  <% end %>
</div>

app/views/tasks/_tags.html.erb
Tag list:
<% task.tags.each do |tag| %>
  <%= link_to tag.content, tag_path(tag) %>
<% end %>

app/views/tasks/edit.html.erb
<div class="container">

  <h1><%= @task.description %></h1>

  <%= form_for [@task.user, @task] do |f| %>

    <%= link_to user_task_path(@task.user, @task), class: "btn btn-default pull-right", id: "delete-button", method: :delete do %>
      <span class="glyphicon glyphicon-remove"></span>
    <% end %>

    <%= f.label :description %><br>
    <%= f.text_field :description %><br><br>
    <%= f.label :category %><br>
    <%= f.text_field :category %><br><br>

    <%= button_tag(type: 'submit', class: 'btn btn-default', id: 'add-button') do %>
      <span class="glyphicon glyphicon-plus"></span>
    <% end %>
  <% end %>
</div>

app/views/tasks/index.html.erb
<div class="container">
  <div class="col-md-2 col-md-offset-2">
    <div class="container">
      <h2>Play</h2>
        <ul>
          <% @play_tasks.each do |task| %>
            <li>
              <%= link_to task.description, user_path(task.user) %>
              <%= "By #{task.user.fname} #{task.user.lname}" %>
            </li>
          <% end %>
        </ul>
    </div>
  </div>
  <div class="col-md-2 col-md-offset-2">
    <div class="container">
      <h2>Work</h2>
        <ul>
          <% @work_tasks.each do |task| %>
            <li>
              <%= link_to task.description, user_path(task.user) %>
              <%= "By #{task.user.fname} #{task.user.lname}" %>
            </li>
          <% end %>
        </ul>
    </div>
  </div>
</div>

app/views/users/home.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-2 col-md-offset-5 well name_display">
      <h1><%= @user.fname %></h1>
      <h2>Score: <%= @user.score %></h2>
      <h2><span class="glyphicon glyphicon-heart"></span> <%= @user.likes %></h2>
    </div>
  </div>
</div>

<div class="container tasks">
  <div class="col-md-6">
    <div class="container">
      <h2>Play</h2>
      <%= render partial: 'tasks/form', locals: { :category => "play" } %>
      <%= render partial: 'tasks/show', locals: { :object => @play_tasks } %>
    </div>
  </div>
  <div class="col-md-6">
    <div class="container">
      <h2>Work</h2>
      <%= render partial: 'tasks/form', locals: { category: "work" } %>
      <%= render partial: 'tasks/show', locals: { :object => @work_tasks } %>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-2 col-md-offset-5 well name_display">
      <h1>Everyone</h1>
      <h2>Score: <%= @users_score %></h2>
      <h2><span class="glyphicon glyphicon-heart"></span> <%= @users_likes %></h2>
    </div>
  </div>
</div>

<div class="users">
  <div class="container">
    <% @users.each do |user| %>
      <div class="row">
        <div class="col-md-3">
          <% if user.id == current_user.id %>
            <%= link_to "ME!", home_path %>
          <% else %>
            <%= link_to user.fname, user_path(user) %>
          <% end %>
        </div>
        <div class="col-md-3">
          Score: <%= user.score %>
        </div>
        <div class="col-md-3">
          Tasks: <%= user.tasks.size %>
        </div>
        <div class="col-md-3">
          <span class="glyphicon glyphicon-heart"></span> <%= user.likes %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-2 col-md-offset-5 well name_display">
      <h1><%= @user.fname %></h1>
      <h2>Score: <%= @user.score %></h2>
      <h2><span class="glyphicon glyphicon-heart"></span> <%= @user.likes %></h2>
    </div>
  </div>
</div>

<div class="container tasks">
  <div class="col-md-6">
    <div class="container">
      <h2>Play</h2>
      <%= render partial: 'tasks/show', locals: { :object => @play_tasks } %>
    </div>
  </div>
  <div class="col-md-6">
    <div class="container">
      <h2>Work</h2>
      <%= render partial: 'tasks/show', locals: { :object => @work_tasks } %>
    </div>
  </div>
</div>